databases:
  - name: budget_qsz9
    databaseName: budget_qsz9
    user: budget_qsz9_user

services:
  - type: web
    name: budget_qsz9
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_qsz9
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false